export const metadata = {
  title: "Shopr Sanity Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (<html lang="en">
    <body
    >
      {children}
    </body>
  </html>
  );
}
